---
- name: Verify Access
  hosts: main
  gather_facts: no
  tasks:
  - name: Grafana
    uri:
      url: http://{{inventory_hostname}}:3000
      follow_redirects: none
      status_code: [302]
  - name: Prometheus
    uri:
      url: http://{{inventory_hostname}}:9090
      follow_redirects: none
      status_code: [302]